"""empty message

Revision ID: 0c28a3904582
Revises: 
Create Date: 2020-02-18 23:12:37.731365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c28a3904582'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genderuser', sa.Enum('WOMAN', 'MAN', 'OTHER', name='gender'), nullable=False),
    sa.Column('datecreated', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('mobilenumber', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=280), nullable=False),
    sa.Column('socialmedia', sa.String(length=280), nullable=True),
    sa.Column('sizetop', sa.String(length=280), nullable=False),
    sa.Column('sizebottom', sa.String(length=280), nullable=False),
    sa.Column('sizeshoes', sa.String(length=280), nullable=False),
    sa.Column('igaccount', sa.String(length=140), nullable=True),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('waist', sa.Integer(), nullable=False),
    sa.Column('armsuser', sa.Enum('SHORT', 'AVERAGE', 'LONGY', name='arms'), nullable=False),
    sa.Column('shouldersuser', sa.Enum('NARROW', 'AVERAGE', 'WIDE', name='shoulders'), nullable=False),
    sa.Column('torsouser', sa.Enum('SHORT', 'AVERAGE', 'LONGY', name='torso'), nullable=False),
    sa.Column('hipsuser', sa.Enum('NARROW', 'AVERAGE', 'WIDE', name='hips'), nullable=False),
    sa.Column('legsuser', sa.Enum('SHORT', 'AVERAGE', 'LONGY', name='legs'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budgettop', sa.Integer(), nullable=True),
    sa.Column('budgetbottom', sa.Integer(), nullable=True),
    sa.Column('budgetshoes', sa.Integer(), nullable=True),
    sa.Column('budgetsportshoes', sa.Integer(), nullable=True),
    sa.Column('budgetbag', sa.Integer(), nullable=True),
    sa.Column('budgetaccesories', sa.Integer(), nullable=True),
    sa.Column('user_userid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('genderuser', sa.Enum('WOMAN', 'MAN', 'OTHER', name='gender'), nullable=False),
    sa.Column('user_userid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dislikes',
    sa.Column('user_userid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fitbottom',
    sa.Column('user_userid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fitbottomorder', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fittop',
    sa.Column('user_userid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fittoporder', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jeans',
    sa.Column('user_userid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jeanschoiceurl', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['user_userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lookchoice',
    sa.Column('user_userid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('look_url', sa.String(length=400), nullable=False),
    sa.Column('lookorder', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occasions',
    sa.Column('user_userid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('occasions')
    op.drop_table('lookchoice')
    op.drop_table('jeans')
    op.drop_table('fittop')
    op.drop_table('fitbottom')
    op.drop_table('dislikes')
    op.drop_table('children')
    op.drop_table('budget')
    op.drop_table('user')
    # ### end Alembic commands ###
